import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import db from "../prisma/db";

type Flower = {
  id: number;
  name: string;
};

export async function getServerSideProps() {
  const flowers: Flower[] = await db.flowers.findMany({
    select: { id: true, name: true },
  });
  return {
    props: {
      flowers: flowers,
    },
  };
}

function Page(props: { flowers: Flower[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hi Yaya!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ol style={{ fontSize: 30 }}>
          {props.flowers.map((flower) => (
            <li key={flower.id}>{flower.name}</li>
          ))}
        </ol>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export default Page;
